language: erlang
sudo: required
dist: trusty

group: edge  # Add this

notifications:
  email:
    on_success: change
    on_failure: always

env:
  - LUA="luajit"

branches:
  only:
    - dev

install:
  - cd GUIDING_PRINCIPLES/ && bash aio.sh && cd ../

before_script:
  - source setup.sh

script:
  - busted . -c --lua=luajit -p="_spec.lua"

after_success:
  - cp luacov.stats.out luacov.report.out
  - bash <(curl -s https://codecov.io/bash)
