language: erlang
sudo: required
dist: trusty

group: edge  # Add this

notifications:
  email:
    on_success: change
    on_failure: always

env:
  - LUA="luajit"

branches:
  only:
    - dev
    - dev_ramesh
    - dev-inder

install:
  - cd GUIDING_PRINCIPLES/ && bash aio.sh && cd ../
  - source setup.sh && sudo ./q_install.sh

before_script:
  - source setup.sh

script:
  - luajit TEST_RUNNER/q_testrunner.lua i ./
  - luacov

after_success:
  - bash <(curl -s https://codecov.io/bash)
