sudo: required
dist: trusty

group: edge  # Add this

language: erlang

env:
  - LUA="luajit"

branches:
  only:
	- dev

install:
  - cd GUIDING_PRINCIPLES/ && bash aio.sh

script: "source setup.sh && busted --lua=${LUA} RUNTIME/COLUMN/code/test/exp/test_vector.lua"

notifications:
  recipients:
    - isingh@nerdwallet.com
  email:
    on_success: change
    on_failure: always
